//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSW.BookLibrary.EntityLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public System.Guid AuthorId { get; set; }
        public System.Guid CategoryId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Author Author { get; set; }
    }
}
